# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GCE_INSTANCE: remember-me
  GCE_INSTANCE_ZONE: asia-northeast3-a
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    # 권한 설정
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # 빌드 - 테스트 제외
    - name: Build with Gradle
      run: ./gradlew build -x test
    # DB 설정
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        character set server: 'utf8'
        mysql database: ${{ secrets.MYSQL_HOST }} 
        mysql user: ${{ secrets.MYSQL_USERNAME }}
        mysql password: ${{ secrets.MYSQL_PASSWORD }}
    # 도커 허브 로그인
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # 도커 빌드 및 푸시
    - name: Docker build ans push
      run: |
        docker build -t remember-me .
        docker tag remember-me ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7}

#   deploy:
#     needs: [ build ]
#     runs-on: ubuntu-latest
#     steps:

    # Google Cloud 인증
    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Publish app to Google App Engine
      run: |
        sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7}
        sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7} remember-me
        sudo docker-compose up
        
    # SSH 접속 후, 배포
#     - name: Deploy to GCE
#       uses: appleboy/ssh-action@master
#       with:
#         host: $
#         username: $
#         key: $
#         passphrase: $
#         envs: GITHUB_SHA
#         script: |
#             sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7}
#             sudo docker tag ${{ secrets.DOCKERHUB_USERNAME }}/remember-me:${GITHUB_SHA::7} remember-me
#             sudo docker-compose up
